version: "3.2"

services:
  pg:
    image: "postgres:13.5"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=feedcloud
    volumes:
      - ./data/postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
