version: "3.2"

services:
  init-db:
    image: feedcloud
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
    command:
      ./initialize-db.sh

  api:
    image: feedcloud
    depends_on:
      - pg
      - init-db
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
    ports:
      - 5000:80
    command:
      gunicorn --bind '0.0.0.0:80' feedcloud.api:app

  dramatiq-worker:
    image: feedcloud
    depends_on:
      - pg
      - rabbitmq
      - init-db
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
      - FC_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    command:
      dramatiq feedcloud.ingest.tasks

  scheduler:
    image: feedcloud
    depends_on:
      - pg
      - rabbitmq
      - init-db
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
      - FC_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    command:
      python -m feedcloud.ingest.scheduler
