version: "3.2"

services:
  api:
    image: feedcloud
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
    ports:
      - 5000:80
    command:
      gunicorn --bind '0.0.0.0:80' feedcloud.api:app

  dramatiq-worker:
    image: feedcloud
    depends_on:
      - pg
      - rabbitmq
      - api
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
      - FC_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    command:
      dramatiq feedcloud.ingest.tasks

  scheduler:
    image: feedcloud
    depends_on:
      - pg
      - rabbitmq
      - api
    environment:
      - FC_DATABASE_URL=postgresql://test:test@pg/feedcloud
      - FC_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    command:
      python -m feedcloud.ingest.scheduler

  pg:
    image: "postgres:13.5"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=feedcloud
    volumes:
      - ./data/postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
